[package]
name = "sbak"
description = "Small file backup tool."
version = "0.1.0"
authors = ["Igaguri <igagurimk@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
failure = "0.1.5"
hex = "0.3.2"
serde = {version="1.0.97", features=["derive"]}
serde_json = "1.0.40"
sha3 = "0.8.2"
tempfile = "3.1.0"