[package]
name = "sbak"
edition = "2018"
description = "Small file backup tool."
<<<<<<< HEAD
version = "0.1.3"
=======
version = "0.1.1"
>>>>>>> 70072f5... docs: Update version
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities"]
keywords = ["cli", "backup"]
authors = ["Igaguri <igagurimk@gmail.com>"]
readme = "README.md"
documentation = "https://docs.rs/sbak"
repository = "https://github.com/IgaguriMK/sbak"


[dependencies]
anyhow = "1.0"
chrono = "0.4.7"
chrono-tz = "0.5.1"
clap = "2.33"
dirs = "2.0.2"
filetime = "0.2.6"
hex = "0.3.2"
log = "0.4.8"
lazy_static = "1.3.0"
serde = {version="1.0.97", features=["derive"]}
serde_json = "1.0.40"
sha3 = "0.8.2"
tempfile = "3.1.0"
thiserror = "1.0.19"
toml = "0.5.1"
